---
version: 0.0.5
slug: hatest1
name: hatest1
description: Simple browser-based my test application  for Home Assistant
url: https://github.com/mdevsmarthome/HA_App_test1
codenotary: mdevsmarthome@gmail.com
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
homeassistant: 2022.10.2
homeassistant_api: true
image: mayakov/hatest1:0.0.5
ingress: true
init: false
map:
  - backup:rw
  - config:rw
  - media:rw
  - share:rw
  - ssl:rw
options:
  dirsfirst: false
  enforce_basepath: true
  git: true
  ignore_pattern:
    - __pycache__
    - .cloud
    - .storage
    - deps
  ssh_keys: []
panel_icon: mdi:wrench
schema:
  dirsfirst: bool
  enforce_basepath: bool
  git: bool
  ignore_pattern:
    - str
  ssh_keys:
    - str